# data frame


In [1]:
import pandas as pd
import numpy as np

In [2]:
x='Manish Singh'
x.split()

['Manish', 'Singh']

In [3]:
from numpy.random import randn
randn(5,4)

array([[-0.91744884, -0.8062306 ,  0.48061458,  0.15610848],
       [ 1.00186358, -0.67351728, -1.80648321, -0.54758353],
       [-0.92524887, -0.78573355,  0.68306344,  0.26424585],
       [ 0.91384088, -0.74892278,  0.61156554, -0.56377745],
       [-0.27037539,  1.76969623,  0.6504272 ,  0.04497716]])

In [4]:
np.random.seed(101)
randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [6]:
df=pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y  Z'.split())
df

W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [8]:
np.random.seed(100)
my_data=randn(5,4)
my_data

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825]])

In [9]:
df=pd.DataFrame(my_data,index='A B C D E'.split(),columns='W X Y  Z'.split())
df

W         X         Y         Z
A -1.749765  0.342680  1.153036 -0.252436
B  0.981321  0.514219  0.221180 -1.070043
C -0.189496  0.255001 -0.458027  0.435163
D -0.583595  0.816847  0.672721 -0.104411
E -0.531280  1.029733 -0.438136 -1.118318

In [14]:
df['W']
### to get a particular column

A   -1.749765
B    0.981321
C   -0.189496
D   -0.583595
E   -0.531280
Name: W, dtype: float64

In [16]:
df[['W','Z']]

W         Z
A -1.749765 -0.252436
B  0.981321 -1.070043
C -0.189496  0.435163
D -0.583595 -0.104411
E -0.531280 -1.118318

In [24]:
df['W+Z']=df['W']+df['Z']
df
### adding columns to data frame

W         X         Y         Z       new       W+Z
A -1.749765  0.342680  1.153036 -0.252436 -2.002202 -2.002202
B  0.981321  0.514219  0.221180 -1.070043 -0.088723 -0.088723
C -0.189496  0.255001 -0.458027  0.435163  0.245668  0.245668
D -0.583595  0.816847  0.672721 -0.104411 -0.688006 -0.688006
E -0.531280  1.029733 -0.438136 -1.118318 -1.649599 -1.649599

In [25]:
df['new3']=[1,2,3,'',5]
df

W         X         Y         Z       new       W+Z new3
A -1.749765  0.342680  1.153036 -0.252436 -2.002202 -2.002202    1
B  0.981321  0.514219  0.221180 -1.070043 -0.088723 -0.088723    2
C -0.189496  0.255001 -0.458027  0.435163  0.245668  0.245668    3
D -0.583595  0.816847  0.672721 -0.104411 -0.688006 -0.688006     
E -0.531280  1.029733 -0.438136 -1.118318 -1.649599 -1.649599    5

In [28]:
df1=df
df1

W         X         Y         Z       new       W+Z new3
A -1.749765  0.342680  1.153036 -0.252436 -2.002202 -2.002202    1
B  0.981321  0.514219  0.221180 -1.070043 -0.088723 -0.088723    2
C -0.189496  0.255001 -0.458027  0.435163  0.245668  0.245668    3
D -0.583595  0.816847  0.672721 -0.104411 -0.688006 -0.688006     
E -0.531280  1.029733 -0.438136 -1.118318 -1.649599 -1.649599    5

In [31]:
df1.drop('W+Z',axis=1)

W         X         Y         Z       new new3
A -1.749765  0.342680  1.153036 -0.252436 -2.002202    1
B  0.981321  0.514219  0.221180 -1.070043 -0.088723    2
C -0.189496  0.255001 -0.458027  0.435163  0.245668    3
D -0.583595  0.816847  0.672721 -0.104411 -0.688006     
E -0.531280  1.029733 -0.438136 -1.118318 -1.649599    5

In [35]:
### for removing coloumns
df4 = df.drop('new',axis = 1)
df4

W         X         Y         Z       W+Z new3
A -1.749765  0.342680  1.153036 -0.252436 -2.002202    1
B  0.981321  0.514219  0.221180 -1.070043 -0.088723    2
C -0.189496  0.255001 -0.458027  0.435163  0.245668    3
D -0.583595  0.816847  0.672721 -0.104411 -0.688006     
E -0.531280  1.029733 -0.438136 -1.118318 -1.649599    5

In [39]:
df.drop('new3',axis=1,inplace = True)
df

W         X         Y         Z       W+Z
A -1.749765  0.342680  1.153036 -0.252436 -2.002202
B  0.981321  0.514219  0.221180 -1.070043 -0.088723
C -0.189496  0.255001 -0.458027  0.435163  0.245668
D -0.583595  0.816847  0.672721 -0.104411 -0.688006
E -0.531280  1.029733 -0.438136 -1.118318 -1.649599

# Row operation


In [43]:
df

W         X         Y         Z       W+Z
A -1.749765  0.342680  1.153036 -0.252436 -2.002202
B  0.981321  0.514219  0.221180 -1.070043 -0.088723
C -0.189496  0.255001 -0.458027  0.435163  0.245668
D -0.583595  0.816847  0.672721 -0.104411 -0.688006
E -0.531280  1.029733 -0.438136 -1.118318 -1.649599

In [47]:
df.drop('E',axis=0,inplace=True)

W         X         Y         Z       W+Z
A -1.749765  0.342680  1.153036 -0.252436 -2.002202
B  0.981321  0.514219  0.221180 -1.070043 -0.088723
C -0.189496  0.255001 -0.458027  0.435163  0.245668
D -0.583595  0.816847  0.672721 -0.104411 -0.688006

In [48]:
df.loc['B']
####  to access the row

W      0.981321
X      0.514219
Y      0.221180
Z     -1.070043
W+Z   -0.088723
Name: B, dtype: float64

In [50]:
df.loc[['A','D']]

W         X         Y         Z       W+Z
A -1.749765  0.342680  1.153036 -0.252436 -2.002202
D -0.583595  0.816847  0.672721 -0.104411 -0.688006

In [51]:
df.iloc[3]
#### iloc will vbe used to system index that is  0,1,2,........

W     -0.583595
X      0.816847
Y      0.672721
Z     -0.104411
W+Z   -0.688006
Name: D, dtype: float64

In [52]:
df.iloc[[0,2]]

W         X         Y         Z       W+Z
A -1.749765  0.342680  1.153036 -0.252436 -2.002202
C -0.189496  0.255001 -0.458027  0.435163  0.245668

In [53]:
df.iloc[1:3]

W         X         Y         Z       W+Z
B  0.981321  0.514219  0.221180 -1.070043 -0.088723
C -0.189496  0.255001 -0.458027  0.435163  0.245668

In [55]:
df.iloc[2:]

W         X         Y         Z       W+Z
C -0.189496  0.255001 -0.458027  0.435163  0.245668
D -0.583595  0.816847  0.672721 -0.104411 -0.688006

In [56]:
df.iloc[1,2]

0.22117966922140045

In [58]:
df.iloc[0,0]

-1.7497654730546974

In [59]:
df.iloc[1,1]

0.5142188413943821

In [60]:
df.iloc[2,3]

0.43516348812289213

In [61]:
df.iloc[2,2]

-0.4580269855026243

In [62]:
df

W         X         Y         Z       W+Z
A -1.749765  0.342680  1.153036 -0.252436 -2.002202
B  0.981321  0.514219  0.221180 -1.070043 -0.088723
C -0.189496  0.255001 -0.458027  0.435163  0.245668
D -0.583595  0.816847  0.672721 -0.104411 -0.688006

In [63]:
df.iloc[0:2,1:2]

X
A  0.342680
B  0.514219

In [64]:
df.iloc[1:3,1:3]

X         Y
B  0.514219  0.221180
C  0.255001 -0.458027

In [65]:
df.iloc[0:4,0:3]

W         X         Y
A -1.749765  0.342680  1.153036
B  0.981321  0.514219  0.221180
C -0.189496  0.255001 -0.458027
D -0.583595  0.816847  0.672721

In [66]:
df.iloc[:,3:4]

Z
A -0.252436
B -1.070043
C  0.435163
D -0.104411

In [67]:
df.iloc[0:3,:]

W         X         Y         Z       W+Z
A -1.749765  0.342680  1.153036 -0.252436 -2.002202
B  0.981321  0.514219  0.221180 -1.070043 -0.088723
C -0.189496  0.255001 -0.458027  0.435163  0.245668

In [68]:
df.iloc[0:2,-2:-1]

Z
A -0.252436
B -1.070043

In [69]:
df.iloc[[1,3],[0,2]]

W         Y
B  0.981321  0.221180
D -0.583595  0.672721

In [72]:
df.loc['A':'C','W':'Y']

W         X         Y
A -1.749765  0.342680  1.153036
B  0.981321  0.514219  0.221180
C -0.189496  0.255001 -0.458027

In [73]:
# condition statement
df>0


W     X      Y      Z    W+Z
A  False  True   True  False  False
B   True  True   True  False  False
C  False  True  False   True   True
D  False  True   True  False  False

In [74]:
df[df>0]

W         X         Y         Z       W+Z
A       NaN  0.342680  1.153036       NaN       NaN
B  0.981321  0.514219  0.221180       NaN       NaN
C       NaN  0.255001       NaN  0.435163  0.245668
D       NaN  0.816847  0.672721       NaN       NaN

In [76]:
df[df['W']>0]['Y']

B    0.22118
Name: Y, dtype: float64

In [77]:
df[df['Y']>0]

W         X         Y         Z       W+Z
A -1.749765  0.342680  1.153036 -0.252436 -2.002202
B  0.981321  0.514219  0.221180 -1.070043 -0.088723
D -0.583595  0.816847  0.672721 -0.104411 -0.688006

In [78]:
df[df['W']>0][['Y','X']]

Y         X
B  0.22118  0.514219